spring:
  application:
    name: FeedMe
  datasource:
    url: jdbc:postgresql://localhost:5432/feedme
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true